baseURL = 'https://lafayettegabe.github.io'
languageCode = 'en-us'
title = 'Gabe'
theme = "github-style"
pygmentsCodeFences = true
pygmentsUseClasses = true

[markup.goldmark.renderer]
  unsafe = true

[frontmatter]
  lastmod = ["lastmod", ":fileModTime", ":default"]

[params]
  author = "Gabe"
  description = "SWE | DevOps | CyberSec"
  userStatusEmoji = "☕"
  email = "gabriel.lafayette@proton.me"
  location = "Porto Alegre, Brazil"

  github = "lafayettegabe"
  bluesky = "gabe.bookstans.com"
  instagram = "soaresgabe"

  avatar = "https://avatars.githubusercontent.com/u/e?email=gabriel.lafayette%40proton.me&s=400"
  headerIcon = "https://avatars.githubusercontent.com/u/e?email=gabriel.lafayette%40proton.me&s=400"
  favicon = "https://github.githubassets.com/favicons/favicon.svg"

  rss = true
  lastmod = true
  enableSearch = true
  enableGitalk = true
  
  [params.gitalk]
    clientID =  "GITALK_CLIENT_ID" 
    clientSecret = "GITALK_CLIENT_SECRET"
    repo = "lafayettegabe.github.io"
    owner = "lafayettegabe"
    admin = ["lafayettegabe"]  
    id = "location.pathname"
    labels = ["gitalk"]
    perPage = 30
    pagerDirection = "last"
    createIssueManually = false
    distractionFreeMode = false

[outputs]
  home = ["html", "RSS", "json"]

[outputFormats.json]
  mediaType = "application/json"
  baseName = "index"
  isPlainText = false
